### ISSUE TITLE
links to explorer are pointing to different domain thus returning not found

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwcbuildpipeline#11]
Please change to relative paths.

**Comment by cgilliard** [comment]
See screenshot (notice url is explorer.floonet.mwc.mw and links are to explorer.mwc.mw.
<img width="1086" alt="Screen Shot 2019-09-11 at 9 31 25 PM" src="https://user-images.githubusercontent.com/7232183/64746957-9426ae00-d4db-11e9-96fe-748cf766e842.png">

**Comment by hcasalet** [comment]
Chris, 

This comes from the proof file itself. The test file that you gave me has explorer.mwc.mw in it? Please look at the lines in VerifyProof.java (line 85-112). We need to use a different test file?

Since this is a full link in the middle of the page, we cannot use relative path, but have to hostname:port# in the java file in order to have correct link?

Thanks,
Holly

**Comment by cgilliard** [comment]
Ok thanks. Fix needs to be in the wallet. Will open a bug for that.

**Comment by ajcryptoR18** [comment]
This file has changed since Sep.  Is the issue still exist?  In my local environment, I am not able to see this issue.  (https://localhost:8445/VerifyProof).  Where I can reproduce this issue?

**Comment by hcasalet** [comment]
Don't worry about this issue. This is not for Block Explorer as it turns out. Chris, do you want to move this issue away and close it from here? Thanks.

**Comment by cgilliard** [comment]
Closing. This was fixed in the Qt wallet.
